#!/usr/bin/env python3
"""
PostgreSQL Database Verification Script
Generated by grok-code-fast-1 API

Verifies PostgreSQL connection and table structure for Toy Wizard Backend
- Checks connection to PostgreSQL database
- Validates all required tables exist (ToyAnalysis, PriceHistory, UserSession, MLModelMetrics)
- Inspects table schemas and indexes
- Tests basic database operations
- Logs all results to app.log

Usage: python3 postgres_verification.py
"""

import asyncio
import logging
import os
import sys
from datetime import datetime
from typing import Dict, List, Any

# Add the app directory to Python path for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

try:
    from sqlalchemy import text, create_engine, MetaData, Table, Column, Integer, String, Float, DateTime, Text
    from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
    from sqlalchemy.orm import sessionmaker
    from dotenv import load_dotenv

    # Load environment variables from the correct .env file path
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '.env')
    load_dotenv(env_path)

    SQLALCHEMY_AVAILABLE = True
except ImportError as e:
    print(f"❌ Missing required packages: {e}")
    print("💡 Install with: pip install sqlalchemy asyncpg python-dotenv")
    SQLALCHEMY_AVAILABLE = False

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('app.log', mode='a'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

class PostgresVerifier:
    """PostgreSQL database verification class"""

    def __init__(self):
        self.database_url = os.getenv('DATABASE_URL')
        self.required_tables = [
            'toy_analyses',      # ToyAnalysis
            'price_history',     # PriceHistory
            'user_sessions',     # UserSession
            'ml_model_metrics'   # MLModelMetrics
        ]
        self.engine = None
        self.async_engine = None

    async def verify_connection(self) -> bool:
        """Verify database connection and basic functionality"""
        try:
            if not self.database_url:
                logger.error("❌ DATABASE_URL not found in environment variables")
                return False

            logger.info(f"🔗 Connecting to database: {self._mask_credentials(self.database_url)}")

            # Create async engine for verification
            if self.database_url.startswith('postgresql://'):
                async_db_url = self.database_url.replace('postgresql://', 'postgresql+asyncpg://')
            else:
                async_db_url = self.database_url

            self.async_engine = create_async_engine(
                async_db_url,
                echo=False,
                pool_size=5,
                max_overflow=10,
                pool_pre_ping=True
            )

            # Test connection
            async with self.async_engine.begin() as conn:
                result = await conn.execute(text("SELECT version()"))
                version = result.scalar()
                logger.info(f"✅ Connected to PostgreSQL: {version}")

                # Get database info
                result = await conn.execute(text("SELECT current_database(), current_user"))
                db_info = result.fetchone()
                logger.info(f"📊 Database: {db_info[0]}, User: {db_info[1]}")

            return True

        except Exception as e:
            logger.error(f"❌ Connection failed: {e}")
            return False

    async def verify_tables(self) -> Dict[str, Any]:
        """Verify all required tables exist and have correct structure"""
        results = {
            'tables_exist': True,
            'table_details': {},
            'total_tables': len(self.required_tables),
            'verified_tables': 0
        }

        try:
            async with self.async_engine.begin() as conn:
                logger.info("🔍 Verifying table existence and structure...")

                for table_name in self.required_tables:
                    table_info = await self._verify_table(conn, table_name)
                    results['table_details'][table_name] = table_info

                    if table_info['exists']:
                        results['verified_tables'] += 1
                        logger.info(f"✅ Table '{table_name}' verified")
                    else:
                        results['tables_exist'] = False
                        logger.error(f"❌ Table '{table_name}' missing")

                # Check for extra tables (optional)
                result = await conn.execute(text("""
                    SELECT table_name
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_type = 'BASE TABLE'
                    ORDER BY table_name
                """))

                all_tables = [row[0] for row in result.fetchall()]
                logger.info(f"📋 All tables in database: {all_tables}")

        except Exception as e:
            logger.error(f"❌ Table verification failed: {e}")
            results['tables_exist'] = False

        return results

    async def _verify_table(self, conn, table_name: str) -> Dict[str, Any]:
        """Verify individual table structure"""
        table_info = {
            'exists': False,
            'row_count': 0,
            'columns': [],
            'indexes': [],
            'constraints': []
        }

        try:
            # Check if table exists
            result = await conn.execute(text("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables
                    WHERE table_schema = 'public'
                    AND table_name = :table_name
                )
            """), {'table_name': table_name})

            table_info['exists'] = result.scalar()

            if not table_info['exists']:
                return table_info

            # Get row count
            result = await conn.execute(text(f"SELECT COUNT(*) FROM {table_name}"))
            table_info['row_count'] = result.scalar()

            # Get columns
            result = await conn.execute(text("""
                SELECT column_name, data_type, is_nullable, column_default
                FROM information_schema.columns
                WHERE table_schema = 'public'
                AND table_name = :table_name
                ORDER BY ordinal_position
            """), {'table_name': table_name})

            table_info['columns'] = [{
                'name': row[0],
                'type': row[1],
                'nullable': row[2],
                'default': row[3]
            } for row in result.fetchall()]

            # Get indexes
            result = await conn.execute(text("""
                SELECT indexname, indexdef
                FROM pg_indexes
                WHERE schemaname = 'public'
                AND tablename = :table_name
                ORDER BY indexname
            """), {'table_name': table_name})

            table_info['indexes'] = [{
                'name': row[0],
                'definition': row[1]
            } for row in result.fetchall()]

            # Get constraints
            result = await conn.execute(text("""
                SELECT tc.constraint_name, tc.constraint_type, kcu.column_name
                FROM information_schema.table_constraints tc
                LEFT JOIN information_schema.key_column_usage kcu
                ON tc.constraint_name = kcu.constraint_name
                WHERE tc.table_schema = 'public'
                AND tc.table_name = :table_name
                ORDER BY tc.constraint_name
            """), {'table_name': table_name})

            table_info['constraints'] = [{
                'name': row[0],
                'type': row[1],
                'column': row[2]
            } for row in result.fetchall()]

        except Exception as e:
            logger.error(f"❌ Error verifying table '{table_name}': {e}")

        return table_info

    async def test_operations(self) -> bool:
        """Test basic database operations"""
        try:
            logger.info("🔧 Testing basic database operations...")

            async with AsyncSession(self.async_engine) as session:
                # Import the actual models
                from app.core.database import ToyAnalysis

                # Test SELECT
                result = await session.execute(text("SELECT COUNT(*) FROM toy_analyses"))
                count = result.scalar()
                logger.info(f"✅ SELECT operation successful (count: {count})")

                # Test INSERT (will be rolled back)
                test_toy = ToyAnalysis(
                    toy_name="Verification Test Toy",
                    category="test",
                    brand="Test Brand",
                    condition_score=9.5,
                    estimated_price=99.99,
                    rarity_score=0.8,
                    confidence=0.95,
                    image_path="/test/verification.jpg",
                    analysis_data='{"verification": "test"}'
                )

                session.add(test_toy)
                await session.rollback()  # Rollback to not persist test data

                logger.info("✅ INSERT operation successful (rolled back)")
                return True

        except Exception as e:
            logger.error(f"❌ Database operations test failed: {e}")
            return False

    def _mask_credentials(self, url: str) -> str:
        """Mask database credentials in URL for logging"""
        if '@' in url:
            protocol = url.split('://')[0]
            credentials = url.split('://')[1].split('@')[0]
            rest = url.split('@')[1]
            return f"{protocol}://***@{rest}"
        return url

    async def run_verification(self) -> Dict[str, Any]:
        """Run complete verification suite"""
        logger.info("=" * 70)
        logger.info("🚀 TOY WIZARD BACKEND - POSTGRESQL VERIFICATION SUITE")
        logger.info("=" * 70)

        verification_results = {
            'timestamp': datetime.now().isoformat(),
            'connection_ok': False,
            'tables_ok': False,
            'operations_ok': False,
            'overall_status': 'FAILED',
            'details': {}
        }

        # 1. Verify connection
        logger.info("📡 Step 1: Verifying database connection...")
        verification_results['connection_ok'] = await self.verify_connection()

        if not verification_results['connection_ok']:
            logger.error("❌ Connection verification failed - aborting")
            return verification_results

        # 2. Verify tables
        logger.info("🔍 Step 2: Verifying table structure...")
        table_results = await self.verify_tables()
        verification_results['details']['tables'] = table_results
        verification_results['tables_ok'] = table_results['tables_exist']

        # 3. Test operations
        logger.info("🔧 Step 3: Testing database operations...")
        verification_results['operations_ok'] = await self.test_operations()

        # Determine overall status
        if verification_results['connection_ok'] and verification_results['tables_ok'] and verification_results['operations_ok']:
            verification_results['overall_status'] = 'SUCCESS'
            logger.info("🎉 All verification checks passed!")
        else:
            verification_results['overall_status'] = 'PARTIAL'
            logger.warning("⚠️ Some verification checks failed")

        # Cleanup
        if self.async_engine:
            await self.async_engine.dispose()

        # Log final results
        logger.info("=" * 70)
        logger.info(f"🎯 VERIFICATION STATUS: {verification_results['overall_status']}")
        logger.info(f"   Connection: {'✅' if verification_results['connection_ok'] else '❌'}")
        logger.info(f"   Tables: {'✅' if verification_results['tables_ok'] else '❌'} ({table_results['verified_tables']}/{table_results['total_tables']})")
        logger.info(f"   Operations: {'✅' if verification_results['operations_ok'] else '❌'}")
        logger.info("=" * 70)

        return verification_results

async def main():
    """Main verification function"""
    if not SQLALCHEMY_AVAILABLE:
        logger.error("❌ Required packages not available")
        return

    verifier = PostgresVerifier()
    results = await verifier.run_verification()

    # Print summary to console
    print("\n" + "=" * 70)
    print("📊 VERIFICATION SUMMARY")
    print("=" * 70)
    print(f"Status: {results['overall_status']}")
    print(f"Connection: {'✅ PASS' if results['connection_ok'] else '❌ FAIL'}")
    print(f"Tables: {'✅ PASS' if results['tables_ok'] else '❌ FAIL'}")
    if 'tables' in results['details']:
        table_info = results['details']['tables']
        print(f"  Verified: {table_info['verified_tables']}/{table_info['total_tables']} tables")
    print(f"Operations: {'✅ PASS' if results['operations_ok'] else '❌ FAIL'}")
    print(f"Timestamp: {results['timestamp']}")
    print("=" * 70)

    return results['overall_status'] == 'SUCCESS'

if __name__ == "__main__":
    success = asyncio.run(main())
    exit(0 if success else 1)